name: Setup OSS CAD Suite

inputs:
  osscadsuite-version:
    description: 'version to install'
    required: true

runs:
  using: composite
  steps:
    - id: cache-oss-cad-suite
      uses: actions/cache@v3
      with:
        path: oss-cad-suite
        key: oss-cad-suite-${{ runner.os }}-${{ inputs.osscadsuite-version }}

    - shell: bash
      if: steps.cache-oss-cad-suite.outputs.cache-hit != 'true'
      run: |
        VERSION=${{ inputs.osscadsuite-version }}
        ARTIFACT=oss-cad-suite-linux-x64-$(echo $VERSION | tr -d '-')
        wget -q -O - https://github.com/YosysHQ/oss-cad-suite-build/releases/download/${VERSION}/${ARTIFACT}.tgz | tar -zx

    # Add the CAD Suite to the PATH
    - shell: bash
      run: echo "$(pwd)/oss-cad-suite/bin" >> $GITHUB_PATH

