name: Chisel Sequences Unittests

on:
  push:
  pull_request:

jobs:
  test-scala:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Tabby OSS Cad Suite (from YosysHQ)
      uses: ./.github/workflows/setup-oss-cad-suite
      with:
        osscadsuite-version: '2023-01-13'

    - name: Install Spot
      run: |
        cd /tmp
        wget -q -O debian.gpg https://www.lrde.epita.fr/repo/debian.gpg
        sudo apt-key add debian.gpg
        sudo add-apt-repository 'deb http://www.lrde.epita.fr/repo/debian/ stable/'
        sudo apt-get update -y
        sudo apt-get install -y spot
        ltl2tgba --version

    - name: Check Formating
      timeout-minutes: 3
      run: sbt scalafmtCheckAll

    - name: Run Unittests
      timeout-minutes: 3
      run: sbt test
