name: Chisel Sequences Unittests

on:
  push:
  pull_request:

jobs:
  test-scala:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Tabby OSS Cad Suite (from YosysHQ)
      uses: YosysHQ/setup-oss-cad-suite@v1
      with:
        osscadsuite-version: '2022-09-30'

    - name: Install Spot
      run: |
        sudo wget -q -O - https://www.lrde.epita.fr/repo/debian.gpg | apt-key add -
        sudo echo 'deb http://www.lrde.epita.fr/repo/debian/ stable/' >> /etc/apt/sources.list
        sudo apt-get update -y
        sudo apt-get install -y spot

    - name: Install Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: openjdk@1.11

    - name: Check Formating
      timeout-minutes: 3
      run: sbt scalafmtCheckAll

    - name: Run Unittests
      timeout-minutes: 3
      run: sbt test
